export const siteCopy = {
  en: {
    themeButton: "Theme",
    telegramButton: "Telegram",
    emailButton: "Email",
    themeSettingsTitle: "Theme settings",
    paletteLabel: "Palette",
    modeLabel: "Mode",
    defaultPaletteLabel: "Default",
    gruvboxPaletteLabel: "Gruvbox",
    lightThemeLabel: "Light",
    darkThemeLabel: "Dark",
    doneLabel: "Done",
    heroTitle: "Helping businesses solve tasks more effectively and improve usability",
    mechtaPeriod: "July 2025 — present",
    productDesignerRole: "Product Designer",
    freelanceName: "Freelance",
    freelancePeriod: "July 2023 — July 2025",
    freelanceRole: "Project-based work · remote",
    bmcPeriod: "February 2024 — August 2024",
    bmcRole: "Project-based work · hybrid",
    aboutTitle: "About",
    aboutParagraphs: [
      "I am a product designer with 3+ years of experience in digital products. I have worked on e-commerce, B2B, retail, AI, and internal tools, including admin panels, process-heavy scenarios, and service interfaces.",
      "I am most interested in work that has to balance usability, business goals, and real implementation. That ranges from mobile apps and customer-facing journeys to internal tools, design systems, and product improvements. I have contributed to 0→1 launches, support of existing products, and steady iteration through prototypes, systems thinking, and close collaboration with teams.",
    ],
    specialProjectsTitle: "Special projects",
    specialProjectsButton: "Press me",
    celebrationDialogLabel: "Celebration",
    celebrationCloseLabel: "Close celebration",
    celebrationTitle: "Hope all your wishes come true!",
    celebrationBody:
      "Inspired by ambition, we unlock potential and make everyday life brighter and more comfortable.",
    celebrationThanks: "Thanks",
    caseOutlineAriaLabel: "Page navigation",
    contextLabel: "Context",
    goalsLabel: "Goals",
    actionsLabel: "Actions",
    metricsLabel: "Metrics and achievements",
    myRoleLabel: "My role",
    resultsLabel: "Results",
    tasksLabel: "What I did",
    problemsLabel: "Problems",
    resultLabel: "Result",
    personalTakeawaysLabel: "Personal takeaways",
    previousCaseLabel: "Previous case",
    nextCaseLabel: "Next case",
    caseCoverPlaceholder: "Case cover / hero visual",
    cvProjectsLabel: "Projects",
    cvResponsibilitiesLabel: "Responsibilities",
    cvResultsLabel: "Results",
    workPageEyebrow: "Work page",
    backlogDescription:
      "This page stores raw, intermediate, and still-unassigned content that has not made it into the main site structure yet. It works as a buffer so materials are not lost between iterations.",
    workflowIntro:
      "This is the internal layer of the case, where context, intermediate steps, trade-offs, team agreements, and decision logic are collected.",
    workflowPublicCaseLabel: "Public case",
    workflowBackToProjectsLabel: "Back to projects",
    soonLabel: "Soon",
    beforeLabel: "Before",
    afterLabel: "After",
    addLabel: "Add",
    imageViewerLabel: "Image viewer",
    imageViewerCloseLabel: "Close image viewer",
  },
  ru: {
    themeButton: "Тема",
    telegramButton: "Telegram",
    emailButton: "Email",
    themeSettingsTitle: "Настройки темы",
    paletteLabel: "Палитра",
    modeLabel: "Режим",
    defaultPaletteLabel: "Стандартная",
    gruvboxPaletteLabel: "Gruvbox",
    lightThemeLabel: "Светлая",
    darkThemeLabel: "Темная",
    doneLabel: "Готово",
    heroTitle: "Помогаю бизнесу эффективнее выполнять задачи и улучшить юзабилити",
    mechtaPeriod: "Июль 2025 — сейчас",
    productDesignerRole: "Продуктовый дизайнер",
    freelanceName: "Фриланс",
    freelancePeriod: "Июль 2023 — июль 2025",
    freelanceRole: "Проектная занятость · онлайн",
    bmcPeriod: "Февраль 2024 — август 2024",
    bmcRole: "Проектная занятость · гибрид",
    aboutTitle: "Обо мне",
    aboutParagraphs: [
      "Я продуктовый дизайнер с 3+ годами опыта в цифровых продуктах. Работал с интернет-магазином, B2B, ритейлом, ИИ и внутренними сервисами, включая админки, процессные сценарии и сервисные интерфейсы.",
      "Сильнее всего мне интересны задачи, где нужно одновременно учитывать usability, бизнес-цели и реальную реализацию: от мобильных приложений и клиентских сценариев до внутренних инструментов, дизайн-систем и продуктовых улучшений. Участвовал в запуске новых решений с нуля, поддержке существующих продуктов и их последовательном улучшении через прототипы, системный подход и тесную работу с командой.",
    ],
    specialProjectsTitle: "Спец проекты",
    specialProjectsButton: "Нажми меня",
    celebrationDialogLabel: "Поздравление",
    celebrationCloseLabel: "Закрыть поздравление",
    celebrationTitle: "Пусть все желания сбудутся!",
    celebrationBody:
      "Вдохновленные мечтой, раскрываем потенциал и делаем жизнь людей ярче, а быт комфортнее.",
    celebrationThanks: "Спасибо",
    caseOutlineAriaLabel: "Навигация по странице",
    contextLabel: "Контекст",
    goalsLabel: "Цели",
    actionsLabel: "Действия",
    metricsLabel: "Метрики и достижения",
    myRoleLabel: "Моя роль",
    resultsLabel: "Результаты",
    tasksLabel: "Задачи",
    problemsLabel: "Проблемы",
    resultLabel: "Результат",
    personalTakeawaysLabel: "Личные итоги",
    previousCaseLabel: "Предыдущий кейс",
    nextCaseLabel: "Следующий кейс",
    caseCoverPlaceholder: "Обложка кейса / hero visual",
    cvProjectsLabel: "Проекты",
    cvResponsibilitiesLabel: "Обязанности",
    cvResultsLabel: "Результаты",
    workPageEyebrow: "Рабочая страница",
    backlogDescription:
      "Сюда складывается нераспределенный, сырой и промежуточный контент, который пока не вошел в основную структуру сайта. Эта страница нужна как рабочий буфер, чтобы не терять материалы между итерациями.",
    workflowIntro:
      "Это внутренний слой кейса, в котором собраны контекст, промежуточные шаги, компромиссы, договоренности с командой и логика выбора решений.",
    workflowPublicCaseLabel: "Публичный кейс",
    workflowBackToProjectsLabel: "Назад к проектам",
    soonLabel: "Скоро",
    beforeLabel: "До",
    afterLabel: "После",
    addLabel: "Добавить",
    imageViewerLabel: "Просмотр изображения",
    imageViewerCloseLabel: "Закрыть просмотр изображения",
  },
};
