export const siteCopy = {
  en: {
    themeButton: "Theme",
    telegramButton: "Telegram",
    emailButton: "Email",
    lightThemeLabel: "Light",
    darkThemeLabel: "Dark",
    heroTitle: "Helping businesses solve tasks more effectively and improve usability",
    mechtaPeriod: "July 2025 — present",
    productDesignerRole: "In-house",
    freelanceName: "Freelance",
    freelancePeriod: "July 2023 — July 2025",
    freelanceRole: "Remote",
    bmcPeriod: "February 2024 — August 2024",
    bmcRole: "Project-based work · hybrid",
    certificatesName: "Courses and certificates",
    certificatesPeriod: "",
    certificatesRole: "Product Design",
    aboutTitle: "About",
    aboutParagraphs: [
      "Product designer with 3 years of experience in e-commerce and internal services. I focus on solving business problems and balancing user experience with development",
    ],
    specialProjectsTitle: "Special projects",
    specialProjectsButton: "Press me",
    celebrationDialogLabel: "Celebration",
    celebrationCloseLabel: "Close celebration",
    celebrationTitle: "Hope all your wishes come true!",
    celebrationBody:
      "Inspired by ambition, we unlock potential and make everyday life brighter and more comfortable.",
    celebrationThanks: "Thanks",
    caseOutlineAriaLabel: "Page navigation",
    contextLabel: "Context",
    goalsLabel: "Goals",
    actionsLabel: "Actions",
    metricsLabel: "Metrics and achievements",
    myRoleLabel: "My role",
    resultsLabel: "Results",
    tasksLabel: "What I did",
    problemsLabel: "Problems",
    resultLabel: "Result",
    previousCaseLabel: "Previous case",
    nextCaseLabel: "Next case",
    ctaTitle: "Get in touch",
    telegramHref: "https://t.me/helloyerik",
    cvHref:
      "https://drive.google.com/file/d/13SuqVNpEbFQW5zAmzso36o-R_6GyYXbj/view?usp=sharing",
    footerCopyright: "© 2026",
    backToTopLabel: "Back to Top",
    caseCoverPlaceholder: "Case cover / hero visual",
    cvProjectsLabel: "Projects",
    cvResponsibilitiesLabel: "Responsibilities",
    cvResultsLabel: "Results",
    workPageEyebrow: "Work page",
    backlogDescription:
      "This page stores raw, intermediate, and still-unassigned content that has not made it into the main site structure yet. It works as a buffer so materials are not lost between iterations",
    workflowIntro:
      "This is the internal layer of the case, where context, intermediate steps, trade-offs, team agreements, and decision logic are collected",
    workflowPublicCaseLabel: "Public case",
    workflowBackToProjectsLabel: "Back to projects",
    soonLabel: "Soon",
    beforeLabel: "Before",
    afterLabel: "After",
    addLabel: "Add",
    imageViewerLabel: "Image viewer",
    imageViewerCloseLabel: "Close image viewer",
  },
  ru: {
    themeButton: "Тема",
    telegramButton: "Telegram",
    emailButton: "Email",
    lightThemeLabel: "Светлая",
    darkThemeLabel: "Темная",
    heroTitle: "Помогаю бизнесу эффективнее выполнять задачи и улучшить юзабилити",
    mechtaPeriod: "Июль 2025 — сейчас",
    productDesignerRole: "Инхаус",
    freelanceName: "Фриланс",
    freelancePeriod: "Июль 2023 — июль 2025",
    freelanceRole: "Онлайн",
    bmcPeriod: "Февраль 2024 — август 2024",
    bmcRole: "Проектная занятость · гибрид",
    certificatesName: "Курсы и сертификаты",
    certificatesPeriod: "",
    certificatesRole: "Продуктовый дизайн",
    aboutTitle: "Обо мне",
    aboutParagraphs: [
      "Я продуктовый дизайнер с 3+ годами опыта, специализация — e-commerce, а также админки и внутренние сервисы, на которых держатся эти продукты",
    ],
    specialProjectsTitle: "Спец проекты",
    specialProjectsButton: "Нажми меня",
    celebrationDialogLabel: "Поздравление",
    celebrationCloseLabel: "Закрыть поздравление",
    celebrationTitle: "Пусть все желания сбудутся!",
    celebrationBody:
      "Вдохновленные мечтой, раскрываем потенциал и делаем жизнь людей ярче, а быт комфортнее.",
    celebrationThanks: "Спасибо",
    caseOutlineAriaLabel: "Навигация по странице",
    contextLabel: "Контекст",
    goalsLabel: "Цели",
    actionsLabel: "Действия",
    metricsLabel: "Метрики и достижения",
    myRoleLabel: "Моя роль",
    resultsLabel: "Результаты",
    tasksLabel: "Задачи",
    problemsLabel: "Проблемы",
    resultLabel: "Результат",
    previousCaseLabel: "Предыдущий кейс",
    nextCaseLabel: "Следующий кейс",
    ctaTitle: "Напишите мне",
    telegramHref: "https://t.me/helloyerik",
    cvHref:
      "https://drive.google.com/file/d/13SuqVNpEbFQW5zAmzso36o-R_6GyYXbj/view?usp=sharing",
    footerCopyright: "© 2026",
    backToTopLabel: "Наверх",
    caseCoverPlaceholder: "Обложка кейса / hero visual",
    cvProjectsLabel: "Проекты",
    cvResponsibilitiesLabel: "Обязанности",
    cvResultsLabel: "Результаты",
    workPageEyebrow: "Рабочая страница",
    backlogDescription:
      "Сюда складывается нераспределенный, сырой и промежуточный контент, который пока не вошел в основную структуру сайта. Эта страница нужна как рабочий буфер, чтобы не терять материалы между итерациями",
    workflowIntro:
      "Это внутренний слой кейса, в котором собраны контекст, промежуточные шаги, компромиссы, договоренности с командой и логика выбора решений",
    workflowPublicCaseLabel: "Публичный кейс",
    workflowBackToProjectsLabel: "Назад к проектам",
    soonLabel: "Скоро",
    beforeLabel: "До",
    afterLabel: "После",
    addLabel: "Добавить",
    imageViewerLabel: "Просмотр изображения",
    imageViewerCloseLabel: "Закрыть просмотр изображения",
  },
};
